ebook_metadata:
  title: ༄༅། །ངེས་དོན་ཕྱག་རྒྱ་ཆེན་པོའི་ཁྲིད་རིམ་གྱི་ཟིན་ཐུན་རྒྱལ་ཀུན་དགྱེས་པའི་གསང་མཛོད་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། མཚུངས་མེད་གྲུབ་པའི་དབང་ཕྱུག་ཤཱཀྱ་ཤྲཱི་ཛྙཱ་ནའི་རྒྱལ་སྲས་འཕགས་མཆོག་རྡོ་རྗེ་མཆོག
  sku: KS-SP-05
  layers:
  - book_title
  - author
  - quotation
  - sabche
web_metadata:
  title:
    en: The Secret Treasury That Brings Joy to All the Buddhas:A Note on Mahamudra
      Instruction
    bo: ངེས་དོན་ཕྱག་རྒྱ་ཆེན་པོའི་ཁྲིད་རིམ་གྱི་ཟིན་ཐུན་རྒྱལ་ཀུན་དགྱེས་པའི་གསང་མཛོད་བཞུགས་སོ།།
  collection:
    en: Se Phakchok Series–  Book 5
    bo: སྲས་འཕགས་མཆོག།–  དེབ། ༥
  author:
    en: Authors:Phakchok Dorje
    bo: འཕགས་མཆོག་རྡོ་རྗེ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-SP-05
  category:
    en: Mahamudra
    bo: ཕྱག་རྒྱ་ཆེན་པོ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-SP-05.epub
  description:
    en: ''
    bo: ''
